services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:$(php artisan key:generate --show)
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
    - MYSQL_ROOT_PASSWORD=4n64nd041523
    - MYSQL_DATABASE=prueba_tecnica
    - MYSQL_USER=root
    - MYSQL_PASSWORD=4n64nd041523
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
